# Generated by Django 4.2.4 on 2023-12-13 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Educationlevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("education_level", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Employeedirectory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("referred_by", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Eventdetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=255)),
                ("event_date", models.DateField()),
                ("location", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Experiencelevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("experience_level", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Gender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Jobrequisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_position", models.CharField(max_length=255)),
                ("event_date", models.DateField()),
                ("location", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Maritalstatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marital_status", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("persona", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Reasonforchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason_for_change", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Screeningmode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("screening_mode", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="CandidateDirectory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recruiter_alert",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                ("role", models.IntegerField(blank=True, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                (
                    "contact_no_primary",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=10, null=True
                    ),
                ),
                (
                    "contact_no_alternate",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=10, null=True
                    ),
                ),
                (
                    "referred_by_other",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "address_line",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "pincode",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=6, null=True
                    ),
                ),
                (
                    "notice_period",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("photo_path", models.TextField(blank=True, null=True)),
                ("resume_path", models.TextField(blank=True, null=True)),
                ("login_time", models.DateTimeField(blank=True, null=True)),
                ("logout_time", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "geo_location",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_date", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.IntegerField(blank=True, null=True)),
                ("modified_date", models.DateTimeField(blank=True, null=True)),
                ("modified_by", models.IntegerField(blank=True, null=True)),
                ("status", models.IntegerField(default=1)),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        db_column="city",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="versionOne.city",
                    ),
                ),
                (
                    "education_level",
                    models.ForeignKey(
                        blank=True,
                        db_column="education_level",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="versionOne.educationlevel",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        db_column="event",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="versionOne.eventdetails",
                    ),
                ),
                (
                    "experience_level",
                    models.ForeignKey(
                        blank=True,
                        db_column="experience_level",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="versionOne.experiencelevel",
                    ),
                ),
                (
                    "gender",
                    models.ForeignKey(
                        blank=True,
                        db_column="gender",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="versionOne.gender",
                    ),
                ),
                (
                    "job_position",
                    models.ForeignKey(
                        blank=True,
                        db_column="job_position",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="versionOne.jobrequisition",
                    ),
                ),
                (
                    "marital_status",
                    models.ForeignKey(
                        blank=True,
                        db_column="marital_status",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="versionOne.maritalstatus",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        blank=True,
                        db_column="persona",
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="versionOne.persona",
                    ),
                ),
                (
                    "reason_for_change",
                    models.ForeignKey(
                        blank=True,
                        db_column="reason_for_change",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="versionOne.reasonforchange",
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="referred_by",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="versionOne.employeedirectory",
                    ),
                ),
                (
                    "screening_mode",
                    models.ForeignKey(
                        blank=True,
                        db_column="screening_mode",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="versionOne.screeningmode",
                    ),
                ),
            ],
            options={
                "db_table": "CandidateDirectory",
            },
        ),
        migrations.AddConstraint(
            model_name="candidatedirectory",
            constraint=models.UniqueConstraint(
                fields=("first_name", "last_name"), name="full_name"
            ),
        ),
    ]
